### ISSUE TITLE
Schimbare premii

### ISSUE THREAD

**Issue by GabrielMajeri** [as-mi/site-smarthack#10]
Ar trebui să apară și logo-ul sponsorului, nu doar suma:

![image](https://user-images.githubusercontent.com/3010346/92276068-fb155200-eef8-11ea-99f9-5e7facfa0c57.png)

**Comment by RaresDumitrica** [comment]
#ce sponsori sunt anul asta?

**Comment by GabrielMajeri** [comment]
Se lucrează la asta :)

**Comment by GabrielMajeri** [comment]
Rezolvat în 26abe56e8f442bd204264252d2a7b1f41b673e51
