### ISSUE TITLE
Adăugare informații despre goodies pe site

### ISSUE THREAD

**Issue by GabrielMajeri** [as-mi/site-smarthack#18]
În loc să avem rubrica „Costă să particip?”, putem pune detalii despre goodies și despre tombolă.

**Comment by RaresDumitrica** [comment]
Si de unde luam detalii idespre goodies si tombola?:))

**Comment by GabrielMajeri** [comment]
Așteptăm detalii de la PMi + responsabilul de goodies :))

**Comment by GabrielMajeri** [comment]
Informațiile despre când sunt tombolele au fost adăugate în 33a8d450235240a9d4300252c39f885284232663
