### ISSUE TITLE
Animație mai rapidă la navbar

### ISSUE THREAD

**Issue by GabrielMajeri** [as-mi/site-smarthack#5]
În momentul în care apeși pe un buton din navbar pagina dă scroll destul de încet

**Comment by GabrielMajeri** [comment]
Rareș a actualizat scroll-ul și acum merge mai rapid.

@Aleksander223 viteza de scroll nouă e ok pentru tine?

**Comment by Aleksander223** [comment]
Da este ok, putem inchide issue-ul
