### ISSUE TITLE
Animație count up pentru cifre

### ISSUE THREAD

**Issue by GabrielMajeri** [as-mi/site-smarthack#6]
Am putea anima numerele care apar pe pagină la secțiunea Despre, să crească de la 0.

**Comment by mehanix** [comment]
pot incerca sa migrez bucata din site-ul Cariere care face asta

**Comment by GabrielMajeri** [comment]
Sună bine. Cum e implementarea acolo?

**Comment by mehanix** [comment]
E cu https://github.com/bfintal/Counter-Up
vad ca avem jquery deja deci n-ar fi a huge deal sa il folosim

**Comment by GabrielMajeri** [comment]
Am văzut pe `README`-ul acelui plugin că recomandă folosirea succesorului [Counter-Up2](https://github.com/bfintal/Counter-Up2). Cred că o să meargă mai bine, mai ales că acela are support și pentru `npm`
