### ISSUE TITLE
Eliminare hartă

### ISSUE THREAD

**Issue by GabrielMajeri** [as-mi/site-smarthack#9]
Nu mai este necesară

**Comment by RaresDumitrica** [comment]
Odata cu schimbarea hartii o sa modific si plaeta de culori din sectiunea 3 [Nu esti din bucuresti, doarece sectiunea 3 si sectiunea 2 impart acelasi background si arata urat]

**Comment by GabrielMajeri** [comment]
Cred că s-a rezolvat, harta a fost eliminată în f910e38d16093fdae355fd2a32c45a2080134949
